# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56b69ba5d8a5898fa78c24cb3288e60c360bfba7616ff473a112555daa4ca2032d9d5dcb8fcbb26bb7941c32fbb68b2949dc56ad120b0ab74f0d3a3e92ba99c0

test:
  secret_key_base: 9c6ae9bdb7610854a338f2c41d6b0e636374021989b65cbbdd5e09bf2a0aa55bdfec98e2928c38e9f9f04cad3ffb2a62e695ed70d320551f46b94e6fd9b11b3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
